services:
  - type: web
    name: f1-fantasy-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
