services:
  - type: web
    name: f1-fantasy-app
    env: python
    buildCommand: pip install -r Backend/requirements.txt
    startCommand: PYTHONPATH=Backend python Backend/app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
